name: Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [ feature/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: arduino/compile-sketches@v1.0.1
        with:
          fqbn: 'esp32:esp32:esp32'
          platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          libraries: |
            - source-url: https://github.com/br3ttb/Arduino-PID-Library.git
            - source-url: https://github.com/me-no-dev/ESPAsyncWebServer.git
            - source-url: https://github.com/me-no-dev/AsyncTCP.git
            - source-url: https://github.com/bblanchon/ArduinoJson.git
            - name: MAX6675 library
            - source-url: https://github.com/jandrassy/ArduinoOTA.git
            - source-url: https://github.com/interactive-matter/aJson.git
          sketch-paths: |
            - 'backend/backend.ino'